export const browserCoreExamples = [
  "clawx browser status",
  "clawx browser start",
  "clawx browser stop",
  "clawx browser tabs",
  "clawx browser open https://example.com",
  "clawx browser focus abcd1234",
  "clawx browser close abcd1234",
  "clawx browser screenshot",
  "clawx browser screenshot --full-page",
  "clawx browser screenshot --ref 12",
  "clawx browser snapshot",
  "clawx browser snapshot --format aria --limit 200",
  "clawx browser snapshot --efficient",
  "clawx browser snapshot --labels",
];

export const browserActionExamples = [
  "clawx browser navigate https://example.com",
  "clawx browser resize 1280 720",
  "clawx browser click 12 --double",
  'clawx browser type 23 "hello" --submit',
  "clawx browser press Enter",
  "clawx browser hover 44",
  "clawx browser drag 10 11",
  "clawx browser select 9 OptionA OptionB",
  "clawx browser upload /tmp/file.pdf",
  'clawx browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "clawx browser dialog --accept",
  'clawx browser wait --text "Done"',
  "clawx browser evaluate --fn '(el) => el.textContent' --ref 7",
  "clawx browser console --level error",
  "clawx browser pdf",
];
