#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${CLAWX_INSTALL_E2E_IMAGE:-${CLAWX_INSTALL_E2E_IMAGE:-clawx-install-e2e:local}}"
INSTALL_URL="${CLAWX_INSTALL_URL:-${CLAWX_INSTALL_URL:-https://clawx.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
CLAWX_E2E_MODELS="${CLAWX_E2E_MODELS:-${CLAWX_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e CLAWX_INSTALL_URL="$INSTALL_URL" \
  -e CLAWX_INSTALL_TAG="${CLAWX_INSTALL_TAG:-${CLAWX_INSTALL_TAG:-latest}}" \
  -e CLAWX_E2E_MODELS="$CLAWX_E2E_MODELS" \
  -e CLAWX_INSTALL_E2E_PREVIOUS="${CLAWX_INSTALL_E2E_PREVIOUS:-${CLAWX_INSTALL_E2E_PREVIOUS:-}}" \
  -e CLAWX_INSTALL_E2E_SKIP_PREVIOUS="${CLAWX_INSTALL_E2E_SKIP_PREVIOUS:-${CLAWX_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
